#!/bin/bash

# Enable/Disable waveform dumping
OMSP_NODUMP=0
export OMSP_NODUMP

# Choose simulator:
#                   - iverilog  : Icarus Verilog  (default)
#                   - cver      : CVer
#                   - verilog   : Verilog-XL
#                   - ncverilog : NC-Verilog
#                   - vcs       : VCS
#                   - vsim      : Modelsim
#                   - isim      : Xilinx simulator
OMSP_SIMULATOR=iverilog
export OMSP_SIMULATOR

###############################################################################
#                            Parameter Check                                  #
###############################################################################
EXPECTED_ARGS=1
if [ $# -ne $EXPECTED_ARGS ]; then
    echo "ERROR    : wrong number of arguments"
    echo "USAGE    : run <test name>"
    echo "Example  : run sandbox"
    echo ""
    echo "Available tests:"
    echo "----------------"
    ls ../src/ --hide=*.s43 --hide=*.asm
    echo ""
    echo "Available Sancus tests <sancus/name>:"
    echo "-------------------------------------"
    ls ../src/sancus/ --hide=*.s43 --hide=*.asm
    echo ""
  exit 1
fi

rm -rf cov_work

../bin/msp430sim $1
