#!/bin/bash

# Disable waveform dumping
OMSP_NODUMP=1
export OMSP_NODUMP

# Choose simulator:
#                   - iverilog  : Icarus Verilog  (default)
#                   - cver      : CVer
#                   - verilog   : Verilog-XL
#                   - ncverilog : NC-Verilog
#                   - vcs       : VCS
#                   - vsim      : Modelsim
#                   - isim      : Xilinx simulator
OMSP_SIMULATOR=iverilog
export OMSP_SIMULATOR

rm -rf ./cov_work
rm -rf ./log/*.log
mkdir  ./log

if [ -z "${__SECRET}" ]; then
    __SECRET=0
fi

echo "run_all_attacks with SECRET=$__SECRET"
export __SECRET

# Sancus-specific tests
stdbuf -oL ../bin/msp430sim gap-attacks/test-env                 | tee ./log/gap-attacks-test-env.log
stdbuf -oL ../bin/msp430sim gap-attacks/B-1-dependent-length     | tee ./log/gap-attacks-B-1-dependent-length.log

# Report regression results
../bin/parse_results

exit $?
