#!/bin/bash

# Disable/enable waveform dumping
OMSP_NODUMP=0
export OMSP_NODUMP

OMSP_SIMULATOR=iverilog
export OMSP_SIMULATOR

__SANCUS_SIM=1
export __SANCUS_SIM

rm -rf ./cov_work
rm -rf ./log/*.log
mkdir  ./log

stdbuf -oL ../bin/msp430sim sancus/sm_dma_test                  | tee ./log/sancus-sm_dma_test.log

# Report regression results
../bin/parse_results
exit $?

