#!/bin/bash

# Disable/enable waveform dumping
OMSP_NODUMP=1
export OMSP_NODUMP

OMSP_SIMULATOR=iverilog
export OMSP_SIMULATOR

rm -rf ./cov_work
rm -rf ./log/*.log
mkdir  ./log

# Sancus-specific tests
stdbuf -oL ../bin/msp430sim sancus/sm_eint                 | tee ./log/sancus-sm_eint.log
stdbuf -oL ../bin/msp430sim sancus/sm_irq                  | tee ./log/sancus-sm_irq.log
stdbuf -oL ../bin/msp430sim sancus/crypto_irq              | tee ./log/sancus-sm_crypto_irq.log
stdbuf -oL ../bin/msp430sim sancus/sm_irq_public_end       | tee ./log/sancus-sm_irq_public_end.log
stdbuf -oL ../bin/msp430sim sancus/sm_irq_exec_violation   | tee ./log/sancus-sm_irq_exec_violation.log
stdbuf -oL ../bin/msp430sim sancus/sm_irq_mem_violation    | tee ./log/sancus-sm_irq_mem_violation.log

stdbuf -oL ../bin/msp430sim sancus/sm_irq_sp_violation     | tee ./log/sancus-sm_irq_sp_violation.log
stdbuf -oL ../bin/msp430sim sancus/stack_guard             | tee ./log/sancus-stack_guard.log

stdbuf -oL ../bin/msp430sim sancus/irq_as_indir_i          | tee ./log/sancus-irq_as_indir_i.log
stdbuf -oL ../bin/msp430sim sancus/sm_illegal_entry        | tee ./log/sancus-sm_illegal_entry.log
stdbuf -oL ../bin/msp430sim sancus/sm_mem_violation        | tee ./log/sancus-sm_mem_violation.log

stdbuf -oL ../bin/msp430sim sancus/sm_dma                  | tee ./log/sancus-sm_dma.log

__SANCUS_SIM=1
export __SANCUS_SIM

stdbuf -oL ../bin/msp430sim sancus/sm_dma_peripheral                  | tee ./log/sancus-sm_dma_peripheral.log
stdbuf -oL ../bin/msp430sim sancus/sm_dma_zero                  | tee ./log/sancus-sm_dma_zero.log

# Report regression results
../bin/parse_results
exit $?
