#! /bin/bash

CLOCK_PERIOD=40.0

function dc() {
    if [ $2 -eq 80 ]; then
        MASTER_KEY="deadbeefcafebabedead"
    elif [ $2 -eq 96 ]; then
        MASTER_KEY="deadbeefcafebabedeadbeef"
    elif [ $2 -eq 128 ]; then
        MASTER_KEY="deadbeefcafebabedeadbeefcafebabe"
    fi

    cmake -DCMAKE_INSTALL_PREFIX=/volume1/scratch/pmaene/Projects/SoteriaHW -DTECHNOLOGY_LIBRARIES_DIR=/volume1/scratch/pmaene/Libraries -DCLOCK_PERIOD=$CLOCK_PERIOD -DNB_MODULES=$1 -DSECURITY=$2 -DMASTER_KEY=$MASTER_KEY ../ > /dev/null 2>&1
    make install > /dev/null 2>&1
    sancus-syn > /dev/null 2>&1

    AREA=$(grep -E "Total cell area:[[:space:]]+([0-9\.]+)" /volume1/scratch/pmaene/Projects/SoteriaHW/share/sancus/rtl/synthesis/results/report.area | grep -o -E "[0-9\.]+")
    NAND2_EQ=$(grep -E "NAND2 equivalent cell area:[[:space:]]+([0-9\.]+)" /volume1/scratch/pmaene/Projects/SoteriaHW/share/sancus/rtl/synthesis/results/report.area | grep -o -E "[0-9\.]{2,}")

    echo "$1 | $AREA $NAND2_EQ"
}

for SECURITY in 80 96 128
do
    echo "-- Security $SECURITY"

    for NB_MODULES in 1 2 4 8 16 24
    do
        dc $NB_MODULES $SECURITY
    done

    echo ""
done
