+incdir+${FULL_INSTALL_RTL_PATH}
+incdir+${FULL_INSTALL_SIM_PATH}
-y ${FULL_INSTALL_RTL_PATH}
-y ${FULL_INSTALL_SIM_PATH}

#omsp_alu.v
#omsp_and_gate.v
#omsp_clock_gate.v
#omsp_clock_module.v
#omsp_clock_mux.v
#omsp_dbg_hwbrk.v
#omsp_dbg_uart.v
#omsp_dbg.v
#omsp_execution_unit.v
#omsp_frontend.v
#omsp_hmac_16bit.v
#omsp_hmac_control.v
#omsp_hmac.v
#omsp_mem_backbone.v
#omsp_multiplier.v
#omsp_register_file.v
#omsp_uart.v
#omsp_scan_mux.v
#omsp_sfr.v
#omsp_spm_control.v
#omsp_spm.v
#omsp_sync_cell.v
#omsp_sync_reset.v
#omsp_wakeup_cell.v
#omsp_watchdog.v
#openMSP430_defines.v
#openMSP430_undefines.v
#openMSP430.v
#spongent_datapath.v
#spongent_fsm.v
#spongent_player.v
#spongent_sbox.v
#spongent.v
#omsp_gpio.v
#omsp_timerA_defines.v
#omsp_timerA_undefines.v
#omsp_timerA.v
#omsp_tsc.v
#msp_debug.v
#ram.v
#registers.v
${FULL_INSTALL_SIM_PATH}/sancus_sim.v
